config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "forecasts#index"
  resources :locations
  resources :forecasts
  resources :hourlyforecasts, controller: 'hourly_forecasts'
  resources :dailyforecasts, controller: 'daily_forecasts'
  get 'hourlychart' => "hourly_forecasts#chart"
end

app/models/location.rb
class Location < ApplicationRecord
    validates_presence_of :name, :lat, :lng, :timezone

    has_many :forecasts, dependent: :destroy

    def create_daily_data(only_current = false)
        existing = forecasts.where('time_taken BETWEEN ? AND ?', sixth_day, to_date)
        if(!only_current && existing.count > 0)
            return;
        end
        
        if(!only_current && forecasts.count > 0)
            forecasts.destroy_all
        end

        if(!only_current)
            insert_current_data(timezone, weather_data)
            insert_hourly_data(timezone, weather_data)
            insert_daily_data(timezone, weather_data)
        else
            forecasts.where(type:"CurrentForecast").destroy_all
            insert_current_data(timezone, weather_data)
        end
    end

    def weather_data
        @weather_data ||= WeatherData.new(lat, lng, timezone, today_date).response
    end

    private

    def today_date
        Date.today
    end

    def to_date
        # today_date.advance(days: 7)
        7.days.after(today_date)
    end

    def sixth_day
        # to_date - 1.day
        1.day.before(to_date)
    end
    
    def insert_current_data(timezone, data)
        Forecast.find_or_create_by(
            time_taken: data['current_weather']['time'],
            temp: data['current_weather']['temperature'],
            code: data['current_weather']['weathercode'],
            utc_offset: Time.now.in_time_zone(timezone).utc_offset,
            timezone: timezone,
            location_id: id,
            type: 'CurrentForecast'
        )
    end

    def insert_hourly_data(timezone, data)
        combined = data['hourly']['time'].zip(
            data['hourly']['weathercode'],
            data['hourly']['temperature_2m']
        )

        combined.each do |combo|
            time = combo[0]
            code = combo[1]
            temp = 0
            
            if combo[2].is_a? Float
                temp = combo[2]
            else
                #binding.pry
                temp = combo[2].value.split('.', -1)[0]
            end

            Forecast.find_or_create_by(
                time_taken: time,
                temp: temp,
                code: code,
                utc_offset: Time.now.in_time_zone(timezone).utc_offset,
                timezone: timezone,
                location_id: id
            )
        end
    end

    def insert_daily_data(timezone, data)
        combined = data['daily']['time'].zip(
            data['daily']['weathercode'], 
            data['daily']['temperature_2m_min'],
            data['daily']['temperature_2m_max'],
            data['daily']['sunrise'],
            data['daily']['sunset']
        )

        combined.each do |combo|
            Forecast.find_or_create_by(
                time_taken: combo[0],
                code: combo[1],
                mintemp: combo[2],
                maxtemp: combo[3],
                sunrise: combo[4],
                sunset: combo[5],
                utc_offset: Time.now.in_time_zone(timezone).utc_offset,
                timezone: timezone,
                location_id: id,
                type: 'DailyForecast'
            )
        end
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :set_location, only: [:show, :edit, :update, :destroy]
    #skip_before_action :verify_authenticity_token
    def index
        @locations = Location.all
    end

    def show
    end

    def new
        @location = Location.new
    end

    def create
        if Location.find_by(location_id: params[:location_id])
            return;
        end
        @location = Location.new(location_params)
        Location.update_all(:is_selected => false)

        if @location.save
            respond_to do |format|
                format.turbo_stream
            end
        else
            render :new, status: :unprocessable_entity
        end
        @location.create_daily_data
    end

    def edit
    end

    def update
        if @location.update(location_params)
            redirect_to locations_path, notice: "location was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @location.destroy

        if Location.all.count > 0
            Location.all.first.update!(:is_selected => true)
        end
        respond_to do |format|
            #format.html { redirect_to location_path, notice: "location was successfully destroyed." }
            format.turbo_stream
        end
    end

    private

    def set_location
        @location = Location.find(params[:id])
    end

    def location_params
        params.require(:location).permit(:name, :lat, :lng, :timezone, :location_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_location.html.erb
<%= turbo_frame_tag location do %>
  <li class="collection-item avatar location-collection-item">
        <%# TODO: replace _top with foracsts %>
        <h5><%= link_to location.name, forecasts_path(location.id), data: { turbo_frame: '_top' } %></h5>

        <%= button_to "Delete",
                      location_path(location),
                      method: :delete,
                      class: "waves-effect waves-light btn secondary-content" %>
  </li>
<% end %>

app/views/locations/create.turbo_stream.erb
<%= turbo_stream.prepend "locations", @location %>
<%= turbo_stream.update Location.new, "" %>

app/views/locations/destroy.turbo_stream.erb
<%= turbo_stream.remove @location %>

app/views/locations/index.html.erb
<%= turbo_stream_from "locations" %>
<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12">
        <div class="row">
          <div class="input-field col s12" data-controller="location-search">
            <i class="material-icons prefix">textsms</i>
            <input type="text" id="autocomplete-input" class="autocomplete">
            <label for="autocomplete-input">Enter City Name</label>
          </div>
        </div>
      </div>
    </div>
  
    <%= turbo_frame_tag Location.new %>
    <ul class="collection with-header location-collection">
      <%= turbo_frame_tag "locations" do %>
          <%= render @locations %>
      <% end %>
    </ul>

  </div>
</div>

app/views/locations/show.html.erb
  <%= link_to sanitize("&larr; Back to locations"), locations_path %>
  <div class="header">
    <h1>
      <%= @location.name %>
    </h1>
  </div>